spring:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    url: jdbc:mysql://hojundb.cd8qcimkew4w.ap-northeast-2.rds.amazonaws.com:3306/stepper
    username: root
    password: x9547029
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000${}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: elasticbeanstalk-ap-northeast-2-880624269172
    credentials:
        accessKey: ${ AWS_ACTION_ACCESS_KEY_ID }
        secretKey: ${ AWS_ACTION_SECRET_ACCESS_KEY }
    region:
        static: ap-northeast-2
    stack:
        auto: false
